### ISSUE TITLE
Apuntes segundo año DAM

### ISSUE THREAD

**Issue by LittleSOwls** [kateBea/Desarrollo-de-Aplicaciones-Multiplataforma#1]
¡Hola!

Sigo tu proyecto desde hace poco y me gustaría saber si vas a subir también los apuntes / ejercicios / etc de segundo año de DAM. Es para hacer esas asignaturas más adelante, ya que este año lo estoy preparando por mi cuenta. 

Un saludo.

**Comment by kateBea** [comment]
Hola. 

Sí claro, subiré también los apuntes de segundo año. Pasa que este es mi primer año de DAM por eso están vacíos los directorios del segundo año.

**Comment by LittleSOwls** [comment]
AHHH, vale. Perdona, es que no lo sabía. Los apuntes de DAM si que los estoy usando y me vienen genial. Gracias por publicarlos <3
